steps:
  - name: node:12
    entrypoint: yarn
    args: ["install"]
  - name: node:12
    entrypoint: yarn
    args: ["test:ci"]
  - name: node:12
    entrypoint: yarn
    args: ["build"]
  - name: gcr.io/cloud-builders/gsutil
    args: [-m, rsync, -R, build, gs://www.wikinalysis.com]
